name: therbe-temp
options:
  generateEmptyDirectories: true
  createIntermediateGroups: true
targets:
  therbe-app-watchOS:
    type: application
    platform: watchOS
    dependencies:
      - target: therbe-app-watchOS.watchkitapp
    settings: 
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.brightdigit.therbe-app-watchOS
        SDKROOT: iphoneos
  therbe-app_iOS:
    type: application
    platform: iOS
    dependencies:
      - target: therbe-framework-iOS
    info:
      path: Application/Info_iOS.plist
      properties:
        CFBundleIdentifier: com.brightdigit.therbe-app-iOS
        CFBundleDisplayName: Therbe
        UILaunchStoryboardName: LaunchScreen
    sources:
      - path: Application/Sources/common
      - path: Application/Sources/iOS
    settings: 
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.brightdigit.therbe-app-iOS
        SUPPORTS_UIKITFORMAC: true
        DERIVE_UIKITFORMAC_PRODUCT_BUNDLE_IDENTIFIER: true
  therbe-app_macOS:
    type: application
    platform: macOS
    dependencies:
      - target: therbe-framework-macOS
    info:
      path: Application/Info_macOS.plist
      properties:
        CFBundleIdentifier: com.brightdigit.therbe-app-macOS
        CFBundleDisplayName: Therbe
        NSPrincipalClass: $(TARGET_NAME:c99extidentifier).Application
    sources:
      - path: Application/Sources/common
      - path: Application/Sources/macOS
    settings: 
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.brightdigit.therbe-app-macOS
  therbe-app-watchOS.watchkitapp.watchkitextension:
    type: watchkit2-extension
    platform: watchOS
    dependencies:
      - target: therbe-framework-watchOS
    info:
      path: Application/Info_watchOS_extension.plist
      properties:
        CFBundleDisplayName: Therbe
        NSExtension:
          NSExtensionAttributes:
            WKAppBundleIdentifier : com.brightdigit.therbe-app-watchOS.watchkitapp
          NSExtensionPointIdentifier: com.apple.watchkit
        WKExtensionDelegateClassName: $(PRODUCT_MODULE_NAME).ExtensionDelegate
        WKWatchOnly: true
    sources:
      - Application/Sources/common
      - Application/Sources/watchOS/Extension
    settings: 
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.brightdigit.therbe-app-watchOS.watchkitapp.watchkitextension
  therbe-app-watchOS.watchkitapp:
    type: application.watchapp2
    platform: watchOS
    dependencies:
      - target: therbe-app-watchOS.watchkitapp.watchkitextension
    info:
      path: Application/Info_watchOS.plist
      properties:
        CFBundleDisplayName: Therbe
        WKWatchKitApp: true
    sources:
      - path: Application/Sources/common
      - path: Application/Sources/watchOS/Application
    settings: 
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.brightdigit.therbe-app-watchOS.watchkitapp
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
  therbe-framework:
    name: therbe-framework-${platform}
    type: framework
    platform: [iOS, macOS, tvOS, watchOS]
    settings:
      base:
        PRODUCT_NAME: Therbe
    info:
      path: Framework/Info_${platform}.plist
      properties:
        CFBundleIdentifier: com.brightdigit.therbe-framework-${platform}
    sources:
      - Framework/Sources/common
      - Framework/Sources/${platform}
      - Framework/Generated/
        
